services:
  node-exporter:
    container_name: hge-node-exporter
    image: ${NODE_EXPORTER_IMAGE}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - ${NODE_EXPORTER_PORT}:9100
    restart: always

  jaeger:
    container_name: hge-jaeger
    image: ${JAEGER_IMAGE}
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - ${JAEGER_UI_PORT}:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 50051:4317 # OTLP gRPC 
      - 50052:4318 # OTLP HTTP 
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
      COLLECTOR_ZIPKIN_HOST_PORT: '9411'

  loki:
    image: ${LOKI_IMAGE}
    ports:
      - ${LOKI_PORT}:3100
    command: -config.file=/etc/loki/local-config.yaml

  otel-collector:
    container_name: hge-otel-collector
    image: ${OTEL_COLLECTOR_IMAGE}
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      # - ./gcp-sa.json:/etc/otel/gcp-sa.json
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    environment:
      DD_API_KEY: ${DD_API_KEY}
      NEW_RELIC_API_KEY: ${NEW_RELIC_API_KEY}
      HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      HONEYCOMB_DATASET: ${HONEYCOMB_DATASET}